rootProject.name = "Adyeshach"

include("plugin")
include("project:common")
include("project:common-api")
include("project:common-impl")
include("project:common-impl-nms")
include("project:common-impl-nms-j17")
include("project:module-bukkit")
include("project:compat-model-engine-v2")
include("project:compat-model-engine-v3")
include("project:module-editor")
include("project:module-language")
include("project:module-legacy-api")
include("project:module-test")
include("project:api-data-serializer")