rootProject.name = "Adyeshach"

include("plugin")
include("project:api-data-serializer")
include("project:api-alkaid-mongodb")
include("project:common")
include("project:common-impl")
include("project:common-impl-nms")
include("project:common-impl-nms-j17")
include("project:common-impl-nms-paper-1.19.4")
include("project:common-impl-nms-paper-1.20")
include("project:module-bukkit")
include("project:compat-beton-quest")
//include("project:compat-dragon-core")
include("project:compat-germ-engine")
include("project:compat-model-engine-v2")
include("project:compat-model-engine-v4")
include("project:module-editor")
include("project:module-language")
include("project:module-legacy-api")
