package ink.ptms.adyeshach.core.entity

/**
 * Adyeshach
 * ink.ptms.adyeshach.core.entity.EntityTypes
 *
 * @author 坏黑
 * @since 2022/6/15 18:08
 */
@Suppress("SpellCheckingInspection")
enum class EntityTypes {

    ALLAY, // 悦灵
    AREA_EFFECT_CLOUD, // 区域效果云
    ARMOR_STAND, // 盔甲架
    ARROW, // 箭
    AXOLOTL, // 美西螈
    BAT, // 蝙蝠
    BEE, // 蜜蜂
    BLAZE, // 烈焰人
    BOAT, // 船
    CHEST_BOAT, // 箱子船
    CAT, // 猫
    CAVE_SPIDER, // 洞穴蜘蛛
    CHICKEN, // 鸡
    COD, // 鳕鱼
    COW, // 牛
    CREEPER, // 苦力怕
    DOLPHIN, // 海豚
    DONKEY, // 驴
    DRAGON_FIREBALL, // 龙火球
    DROWNED, // 溺尸
    ELDER_GUARDIAN, // 远古守卫者
    END_CRYSTAL, // 末影水晶
    ENDER_DRAGON, // 末影龙
    ENDERMAN, // 末影人
    ENDERMITE, // 末影螨
    EVOKER, // 唤魔者
    EVOKER_FANGS, // 唤魔者尖牙
    EXPERIENCE_ORB, // 经验球
    EYE_OF_ENDER, // 末影之眼
    FALLING_BLOCK, // 下落的方块
    FIREWORK_ROCKET, // 烟花火箭
    FOX, // 狐狸
    GHAST, // 恶魂
    GIANT, // 巨人
    GLOW_ITEM_FRAME, // 发光物品展示框
    GLOW_SQUID, // 发光鱿鱼
    GOAT, // 山羊
    GUARDIAN, // 守卫者
    HOGLIN, // 疣猪兽
    HORSE, // 马
    HUSK, // 尸壳
    ILLUSIONER, // 幻术师
    IRON_GOLEM, // 铁傀儡
    ITEM, // 物品
    ITEM_FRAME, // 物品展示框
    FIREBALL, // 火球
    LEASH_KNOT, // 拴绳结
    LLAMA, // 羊驼
    LLAMA_SPIT, // 羊驼唾液
    MAGMA_CUBE, // 岩浆怪
    MINECART, // 矿车
    MINECART_CHEST, // 箱子矿车
    MINECART_COMMAND, // 命令方块矿车
    MINECART_FURNACE, // 动力矿车
    MINECART_HOPPER, // 漏斗矿车
    MINECART_MOB_SPAWNER, // 刷怪笼矿车
    MINECART_TNT, // TNT矿车
    MULE, // 骡
    MUSHROOM, // 蘑菇牛
    OCELOT, // 豹猫
    PAINTING, // 画
    PANDA, // 熊猫
    PARROT, // 鹦鹉
    PHANTOM, // 幻翼
    PIG, // 猪
    PIGLIN, // 猪灵
    PIGLIN_BRUTE, // 猪灵蛮兵
    PILLAGER, // 掠夺者
    POLAR_BEAR, // 北极熊
    PRIMED_TNT, // 点燃的TNT
    PUFFERFISH, // 河豚
    RABBIT, // 兔子
    RAVAGER, // 劫掠兽
    SALMON, // 鲑鱼
    SHEEP, // 羊
    SHULKER, // 潜影贝
    SHULKER_BULLET, // 潜影贝子弹
    SILVERFISH, // 蠹虫
    SKELETON, // 骷髅
    SKELETON_HORSE, // 骷髅马
    SLIME, // 史莱姆
    SMALL_FIREBALL, // 小火球
    SNOW_GOLEM, // 雪傀儡
    SNOWBALL, // 雪球
    SPECTRAL_ARROW, // 光灵箭
    SPIDER, // 蜘蛛
    SQUID, // 鱿鱼
    STRAY, // 流浪者
    STRIDER, // 炽足兽
    THROWN_EGG, // 丢出的鸡蛋
    THROWN_ENDER_PEARL, // 丢出的末影珍珠
    THROWN_EXPERIENCE_BOTTLE, // 丢出的经验瓶
    THROWN_POTION, // 丢出的药水
    THROWN_TRIDENT, // 丢出的三叉戟
    TRADER_LLAMA, // 商人羊驼
    TROPICAL_FISH, // 热带鱼
    TURTLE, // 海龟
    VEX, // 恼鬼
    VILLAGER, // 村民
    VINDICATOR, // 卫道士
    WANDERING_TRADER, // 流浪商人
    WITCH, // 女巫
    WARDEN, // 监守者
    WITHER, // 凋灵
    WITHER_SKELETON, // 凋灵骷髅
    WITHER_SKULL, // 凋灵头颅
    WOLF, // 狼
    ZOGLIN, // 僵尸疣猪兽
    ZOMBIE, // 僵尸
    ZOMBIE_HORSE, // 僵尸马
    ZOMBIE_VILLAGER, // 僵尸村民
    ZOMBIE_PIGMAN, // 僵尸猪人
    ZOMBIFIED_PIGLIN, // 僵尸猪灵
    PLAYER, // 玩家
    FISHING_HOOK, // 鱼钩
    FROG, // 青蛙
    TADPOLE, // 蝌蚪
    INTERACTION, // 交互
    TEXT_DISPLAY, // 文本显示
    ITEM_DISPLAY, // 物品显示
    BLOCK_DISPLAY, // 方块显示
    SNIFFER, // 嗅探兽
    CAMEL, // 骆驼
    ARMADILLO, // 犰狳
    OMINOUS_ITEM_SPAWNER, // 不祥之物生成器
    BOGGED, // 沼骸
    BREEZE, // 旋风人
    BAMBOO_RAFT, // 竹筏
    ACACIA_BOAT, // 金合欢木船
    BIRCH_BOAT, // 白桦木船
    CHERRY_BOAT, // 樱花木船
    DARK_OAK_BOAT, // 深色橡木船
    JUNGLE_BOAT, // 丛林木船
    MANGROVE_BOAT, // 红树木船
    OAK_BOAT, // 橡木船
    PALE_OAK_BOAT, // 苍白橡木船
    SPRUCE_BOAT, // 云杉木船
    BAMBOO_CHEST_RAFT, // 运输竹筏
    ACACIA_CHEST_BOAT, // 金合欢木运输船
    BIRCH_CHEST_BOAT, // 白桦木运输船
    CHERRY_CHEST_BOAT, // 樱花木运输船
    DARK_OAK_CHEST_BOAT, // 深色橡木运输船
    JUNGLE_CHEST_BOAT, // 丛林木运输船
    MANGROVE_CHEST_BOAT, // 红树木运输船
    OAK_CHEST_BOAT, // 橡木运输船
    PALE_OAK_CHEST_BOAT, // 苍白橡木运输船
    SPRUCE_CHEST_BOAT, // 云杉木运输船
    WIND_CHARGE, // 风弹
    CREAKING, // 嘎枝
    FISHING_BOBBER, // 浮漂
    COPPER_GOLEM, // 铜傀儡
}